# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-11 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_current_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='checks_assigned',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
