# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-12 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_member_checks_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='checks_assigned',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
