# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-12 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20170912_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='checks_assigned',
            field=models.TextField(blank=True),
        ),
    ]
