# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-22 12:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20170911_1219'),
        ('accounts', '0007_member_priority'),
    ]

    operations = [
    ]
