# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-25 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_merge_20170922_1533'),
        ('accounts', '0008_auto_20170925_1116'),
    ]

    operations = [
    ]
