# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-25 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20170925_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='priority',
            field=models.CharField(default='LOW', max_length=4),
        ),
    ]
