# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-14 09:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='created',
            new_name='created_date',
        ),
    ]
