# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-14 12:17
from __future__ import unicode_literals

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_auto_20170914_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='content',
        ),
        migrations.RemoveField(
            model_name='video',
            name='title',
        ),
        migrations.AddField(
            model_name='video',
            name='video_url',
            field=embed_video.fields.EmbedVideoField(default=True),
            preserve_default=False,
        ),
    ]
