# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-14 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_auto_20170914_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(default=True, max_length=200),
            preserve_default=False,
        ),
    ]
