# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-08 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20160415_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='alert_before',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
