# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-15 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20170912_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='department',
        ),
        migrations.RemoveField(
            model_name='department',
            name='name',
        ),
        migrations.RemoveField(
            model_name='department',
            name='team',
        ),
        migrations.AddField(
            model_name='department',
            name='department_name',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
