# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-12 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20170912_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='often',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='check',
            name='status',
            field=models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('new', 'New'), ('paused', 'Paused')], default='new', max_length=6),
        ),
    ]
