# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-15 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20170915_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_type',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
