# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-15 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_remove_department_department_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='department_name',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
