# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-15 14:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20170914_2015'),
        ('api', '0030_auto_20170912_0827'),
    ]

    operations = [
    ]
