# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-18 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20170912_1210'),
        ('api', '0031_merge_20170915_1713'),
    ]

    operations = [
    ]
