# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-21 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_merge_20170915_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='prioity',
            field=models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('new', 'New'), ('paused', 'Paused'), ('often', 'Often')], default='low', max_length=6),
        ),
    ]
