# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-25 04:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0031_merge_20170915_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('integration_name', models.CharField(default='', max_length=20)),
                ('value', models.TextField(blank=True)),
                ('value_store', models.URLField()),
                ('value_api_key', models.TextField()),
                ('value_store_password', models.TextField()),
                ('checks', models.ManyToManyField(to='api.Check')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
