# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-15 09:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20170915_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='department_name',
        ),
    ]
