# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-15 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_remove_check_department_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='department_name',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
