# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-21 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20170921_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='priority',
            field=models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('new', 'New'), ('paused', 'Paused'), ('often', 'Often')], default='LOW', max_length=6),
        ),
    ]
