# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-25 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20170921_1515'),
        ('api', '0032_merge_20170918_1722'),
    ]

    operations = [
    ]
