# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-15 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_check_dept'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check',
            old_name='dept',
            new_name='department',
        ),
    ]
